import Head from 'next/head'

import { CounterProvider } from '../context/PageContext'
import '../styles/globals.css'



function MyApp({ Component, pageProps }) {

  return (
    <>
      <Head>
        <title>Franklin Mtz </title>
        <meta name="description" content="Generated by create next app" />
        <script async src="https://kit.fontawesome.com/5fa83d646f.js"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CounterProvider>
        <Component {...pageProps} />
      </CounterProvider>
    </>
  )
}

export default MyApp
